/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Illiak' at '5/6/16 12:24 PM' with Gradle 2.13
 *
 * @author Illiak, @date 5/6/16 12:24 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
